import { PrismaClient } from '@prisma/client';

const prismaClient = new PrismaClient();

const populateProducts = async () => {
  await prismaClient.product.createMany({
    data: [
      {
        id: 1,
        price: 10,
        discount: 1,
        name: 'Test 1',
        description: 'Test description 1',
        imageURL: 'https://picsum.photos/id/1/200/300',
      },
      {
        id: 2,
        price: 20,
        discount: 2,
        name: 'Test 2',
        description: 'Test description 2',
        imageURL: 'https://picsum.photos/id/2/200/300',
      },
      {
        id: 3,
        price: 30,
        discount: 3,
        name: 'Test 3',
        description: 'Test description 3',
        imageURL: 'https://picsum.photos/id/3/200/300',
      },
      {
        id: 4,
        price: 40,
        discount: 4,
        name: 'Test 4',
        description: 'Test description 4',
        imageURL: 'https://picsum.photos/id/4/200/300',
      },
      {
        id: 5,
        price: 50,
        discount: 5,
        name: 'Test 5',
        description: 'Test description 5',
        imageURL: 'https://picsum.photos/id/5/200/300',
      },
      {
        id: 6,
        price: 60,
        discount: 6,
        name: 'Test 6',
        description: 'Test description 6',
        imageURL: 'https://picsum.photos/id/6/200/300',
      },
      {
        id: 7,
        price: 70,
        discount: 7,
        name: 'Test 7',
        description: 'Test description 7',
        imageURL: 'https://picsum.photos/id/7/200/300',
      },
      {
        id: 8,
        price: 80,
        discount: 8,
        name: 'Test 8',
        description: 'Test description 8',
        imageURL: 'https://picsum.photos/id/8/200/300',
      },
      {
        id: 9,
        price: 90,
        discount: 9,
        name: 'Test 9',
        description: 'Test description 9',
        imageURL: 'https://picsum.photos/id/9/200/300',
      },
      {
        id: 10,
        price: 100,
        discount: 10,
        name: 'Test 10',
        description: 'Test description 10',
        imageURL: 'https://picsum.photos/id/10/200/300',
      },
      {
        id: 11,
        price: 110,
        discount: 11,
        name: 'Test 11',
        description: 'Test description 11',
        imageURL: 'https://picsum.photos/id/11/200/300',
      },
      {
        id: 12,
        price: 120,
        discount: 12,
        name: 'Test 12',
        description: 'Test description 12',
        imageURL: 'https://picsum.photos/id/12/200/300',
      },
      {
        id: 13,
        price: 130,
        discount: 13,
        name: 'Test 13',
        description: 'Test description 13',
        imageURL: 'https://picsum.photos/id/13/200/300',
      },
      {
        id: 14,
        price: 140,
        discount: 14,
        name: 'Test 14',
        description: 'Test description 14',
        imageURL: 'https://picsum.photos/id/14/200/300',
      },
      {
        id: 15,
        price: 150,
        discount: 15,
        name: 'Test 15',
        description: 'Test description 15',
        imageURL: 'https://picsum.photos/id/15/200/300',
      },
      {
        id: 16,
        price: 160,
        discount: 16,
        name: 'Test 16',
        description: 'Test description 16',
        imageURL: 'https://picsum.photos/id/16/200/300',
      },
      {
        id: 17,
        price: 170,
        discount: 17,
        name: 'Test 17',
        description: 'Test description 17',
        imageURL: 'https://picsum.photos/id/17/200/300',
      },
      {
        id: 18,
        price: 180,
        discount: 18,
        name: 'Test 18',
        description: 'Test description 18',
        imageURL: 'https://picsum.photos/id/18/200/300',
      },
      {
        id: 19,
        price: 190,
        discount: 19,
        name: 'Test 19',
        description: 'Test description 19',
        imageURL: 'https://picsum.photos/id/19/200/300',
      },
      {
        id: 20,
        price: 200,
        discount: 20,
        name: 'Test 20',
        description: 'Test description 20',
        imageURL: 'https://picsum.photos/id/19/200/300',
      },
      {
        id: 21,
        price: 210,
        discount: 21,
        name: 'Test 21',
        description: 'Test description 21',
        imageURL: 'https://picsum.photos/id/21/200/300',
      },
      {
        id: 22,
        price: 220,
        discount: 22,
        name: 'Test 22',
        description: 'Test description 22',
        imageURL: 'https://picsum.photos/id/22/200/300',
      },
      {
        id: 23,
        price: 230,
        discount: 23,
        name: 'Test 23',
        description: 'Test description 23',
        imageURL: 'https://picsum.photos/id/23/200/300',
      },
      {
        id: 24,
        price: 240,
        discount: 24,
        name: 'Test 24',
        description: 'Test description 24',
        imageURL: 'https://picsum.photos/id/24/200/300',
      },
      {
        id: 25,
        price: 250,
        discount: 25,
        name: 'Test 25',
        description: 'Test description 25',
        imageURL: 'https://picsum.photos/id/25/200/300',
      },
      {
        id: 26,
        price: 260,
        discount: 26,
        name: 'Test 26',
        description: 'Test description 26',
        imageURL: 'https://picsum.photos/id/26/200/300',
      },
      {
        id: 27,
        price: 270,
        discount: 27,
        name: 'Test 27',
        description: 'Test description 27',
        imageURL: 'https://picsum.photos/id/27/200/300',
      },
      {
        id: 28,
        price: 280,
        discount: 28,
        name: 'Test 28',
        description: 'Test description 28',
        imageURL: 'https://picsum.photos/id/28/200/300',
      },
      {
        id: 29,
        price: 290,
        discount: 29,
        name: 'Test 29',
        description: 'Test description 29',
        imageURL: 'https://picsum.photos/id/29/200/300',
      },
      {
        id: 30,
        price: 300,
        discount: 30,
        name: 'Test 30',
        description: 'Test description 30',
        imageURL: 'https://picsum.photos/id/30/200/300',
      },
      {
        id: 31,
        price: 310,
        discount: 31,
        name: 'Test 31',
        description: 'Test description 31',
        imageURL: 'https://picsum.photos/id/31/200/300',
      },
      {
        id: 32,
        price: 320,
        discount: 32,
        name: 'Test 32',
        description: 'Test description 32',
        imageURL: 'https://picsum.photos/id/32/200/300',
      },
      {
        id: 33,
        price: 330,
        discount: 33,
        name: 'Test 33',
        description: 'Test description 33',
        imageURL: 'https://picsum.photos/id/33/200/300',
      },
      {
        id: 34,
        price: 340,
        discount: 34,
        name: 'Test 34',
        description: 'Test description 34',
        imageURL: 'https://picsum.photos/id/34/200/300',
      },
      {
        id: 35,
        price: 350,
        discount: 35,
        name: 'Test 35',
        description: 'Test description 35',
        imageURL: 'https://picsum.photos/id/35/200/300',
      },
      {
        id: 36,
        price: 360,
        discount: 36,
        name: 'Test 36',
        description: 'Test description 36',
        imageURL: 'https://picsum.photos/id/36/200/300',
      },
      {
        id: 37,
        price: 370,
        discount: 37,
        name: 'Test 37',
        description: 'Test description 37',
        imageURL: 'https://picsum.photos/id/37/200/300',
      },
      {
        id: 38,
        price: 380,
        discount: 38,
        name: 'Test 38',
        description: 'Test description 38',
        imageURL: 'https://picsum.photos/id/38/200/300',
      },
      {
        id: 39,
        price: 390,
        discount: 39,
        name: 'Test 39',
        description: 'Test description 39',
        imageURL: 'https://picsum.photos/id/39/200/300',
      },
      {
        id: 40,
        price: 400,
        discount: 40,
        name: 'Test 40',
        description: 'Test description 40',
        imageURL: 'https://picsum.photos/id/40/200/300',
      },
    ],
  });
};

const populateDatabase = async () => {
  await populateProducts();
  await prismaClient.$disconnect();
};

populateDatabase();
